### ISSUE TITLE
Possible issues in download data tools

### ISSUE THREAD

**Issue by KPunktRPunkt** [SciCompMod/memilio#107]
Here are listes some small questions and tasks which arised some time ago. A lot of changes have been aplies since then. It should be checked if the problems are still relevant and than they should be solved or a corresponding issue should be opened.

- [x] Do we have the case, that we have to distinguish between empty enties in data and zero for this case. Because pandas treats empty like zeros. However, for us it could be important if there are no ICU_ventilated or if there are no entries about it.
- [x] Date treatment for RKI data shifts time by 1-2 hours. This might also alter the date.
- [x] Why did we need dt.tz_localize('Europe/Berlin') in the beginning for download of rki data and than had to remove it?

**Comment by annette-lutz** [comment]
New data from github only contains dates without time of the day, so point 2 and 3 are outdated.
