### ISSUE TITLE
Improve speed of the IDE model

### ISSUE THREAD

**Issue by lenaploetzke** [SciCompMod/memilio#1077]
### Motivation / Current Behaviour

Currently, simulation with the IDE model takes a long time, especially with small time step sizes, e.g. 1e-4.  (several hours for a simulation time of 35 days in release mode)

### Enhancement description

We should try to reduce the runtime. An experiment in Valgrind has demonstrated that a significant proportion of the runtime is allocated to the evaluation of the StateAgeFunctions. As the same StateAgeFunction is currently evaluated several times at the same time point, the potential for saving runtime could be highest here.

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by lenaploetzke** [comment]
@annawendler Is this actually also resolved by #1129 ?

**Comment by annawendler** [comment]
I would say so for now.

**Comment by annawendler** [comment]
As the run time of the IDE model was reduced significantly in #1129, we consider this issue resolved for now.
