### ISSUE TITLE
Explore using ccache for CI pipeline

### ISSUE THREAD

**Issue by dabele** [SciCompMod/memilio#305]
ccache could reduce the load and runtime of our pipeline a lot, since most files don't change in a pull request. How much can be gained needs to be tested, since use of templates makes ccache less efficient because there are fewer compilation units overall and changes are more likely.

**Comment by dabele** [comment]
time measurements with ccache on my workstation using 4 processes:

- 3:52 min with empty cache
- 3:22 with change io.h, included almost everywhere in our code, basically only the dependencies (boost, etc) are cached
- 2:50 with change to time_series.h, used on many places, some unittests and other cpp files are cached
- 0:52 with change to date.h, included in only a few files
- 0:51 with change to parameters.h, only used in one model

With higher parallelism, the use of the cache goes down. With 16 processes:
- 1:58 empty cache
- 1:45 with changing io.h
- 0:49 with changing parameters.h

Observations:
- even when only a handful of files need to be compiled as in the parameters.h case, linking still takes a long time e.g. because linking of unittest executable needs to be done if only one translation unit changed. Maybe separating the unittests into smaller packets could reduce times here?
- with ccache, parallel build is worth much less in terms of runtime. Overall resource consumption is still reduced.
- very reliable gains come form caching dependencies like boost, which almost never change. but these gains could be achieved by using conan package manager as well (see #187)

**Comment by dabele** [comment]
Miscellaneous notes on ccache:
- integrate into cmake build by setting variable CMAKE_CXX_COMPILER_LAUNCHER=ccache
- cache size can be configured and should be big enough to hold a few versions at the same time so that, e.g., two pull requests and the nightly build that all build different versions don't interfere with each other's cache.
- By default, the cache includes the working directory. this should be disabled, so that builds in different places in the repository (e.g. on in pycode and one in cpp) can use the same cache

**Comment by mknaranja** [comment]
@dabele Could you upload your configurations to a branch?
