### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by mknaranja** [SciCompMod/memilio#350]
For better references to our software, we should prepare a release over the next months.

Feel free to discuss what should be integrated, optimized, added until then.

**Comment by mknaranja** [comment]
Carlotta's ABM works:
- location capacities
- masks

**Comment by HenrZu** [comment]
ODE:

-  Rework visualization tools
- new model with waining immunity
- commuter/mobility scheme (?)

surrogate model:

- Secir simple network structure
- Secir age group network structure
- Examples & documentation
- Unit tests

**Comment by mknaranja** [comment]
I think surrogate models will be too much for the release end of this year.

**Comment by xsaschako** [comment]
Also as a next step, which might be too much for this release, would be a parameter calibration. This would be the next step, after the data from Braunschweig is implemented, and we can optimize the parameters regarding them.

**Comment by mknaranja** [comment]
We should not forget to provide a CITATION.cff file.

**Comment by xsaschako** [comment]
@mknaranja mark as done? :-)
