### ISSUE TITLE
Responsibility of Testing Schemes regarding quarantine

### ISSUE THREAD

**Issue by DavidKerkmann** [SciCompMod/memilio#367]
To be allowed to enter a (new) location, ALL testing schemes have to allow a person to go there. Since quarantine is handled by the MigrationRules, if you would call run_strategy twice, and there is no testing scheme with minimal time = 0, then it could actually change the result from the first call. Calling it twice in a row thus has to be avoided. Right now, this is fine since run_strategy is only ever called once for each location (where quarantine has already be checked for in the MigrationRules).

**Comment by DavidKerkmann** [comment]
To add something to the discussion: In general, it is a good that the testing schemes are not responsible for the quarantine checks but only for testing and evaluating testing results. Thus, it could be enough to update the description of the return type of `run_scheme` to account for this fact.

**Comment by DavidKerkmann** [comment]
The important part here is that currently no-one is released from quarantine, because the movement rules don't call the testing strategy (and therefore the tests) when a person is in quarantine. We need a mechanism that removes the quarantine somehow. This could be after a time or/and after a test is performed that was negative.
The handling of quarantine may not always be the same, depending on government and the type of virus. However, I propose that we go for a "freitesten" approach for now. So one could say that after a person enters quarantine, daily antigen tests are conducted and when there is a negativ one, a PCR follows to confirm and then remove the quarantine if it's negative.
The work in #866 should be taken into account and compared with, as it adds delays in testing.

**Comment by xsaschako** [comment]
Quick notes for me to discuss:
- This probably makes things more complicated, but should we even have m_minimal_time_since_last_test ? in accordance to #866 there we already save the validity of a test and then can check for that`(if e.g. tests match -> automatically pass)? Con: this would prob lead to performance problems and we need time_since last test anyway.
- In NRW we had 10 days for not testing, e.g. automatically cancel quarantine after 10 days.
- After 5 days one could free themselves from quarantine with a PCR and normal test (side thiught: maybe differentiate between self etsting and official testing...)  as both tests had to be official, i would go for the PCR test right now

**Comment by xsaschako** [comment]
Quick fix in respect to time: we just set qurantine as fals after 5 days
sidenote: time_since_last_test to be set after set to 0
