### ISSUE TITLE
Write mobility data

### ISSUE THREAD

**Issue by maccxs** [SciCompMod/memilio#55]
* aim: if necessary, migration data is collected and written in an hdf-5 file
* integrate and refactor the code for migration data (from dlr-repo)
* for the moment we decided against the more general "callback"-option
* a bool that tells the simulation that mirgration data is needed
* data will be aggregated over age groups
* percentiles will be computed over the number of runs
* all compartments are written that are allowed to migrate (all whose baseline migration param is not zero, maybe)
* store and write a time series for each edge
* generalize HDF5-write so that the data can be written and existing functions are reused; an annotation is necessary to know from what node to what other node people migrated

**Comment by mknaranja** [comment]
@HenrZu To fulfill https://github.com/DLR-SC/LOKI-User-Stories/issues/61, we should implement this until End of February 2024.

**Comment by HenrZu** [comment]
As discussed, the current plan is to aggregate all age groups first. To save further capacity, we only want to write out the NoSymptoms and Symptoms compartments. Next, we also include the total number of travelers. 

Next step, we should try to create an initial draft for creating this data set using the model (SecirVVS).

**Comment by mknaranja** [comment]
If possible, that data would have structure
```
- region_id_1
  - to_region_id_1 (actually id_1 -> id_1 is superfluous but no need to remove, as only minor increase in data storage)
    - time: time points
    - total: Asymptomatic, Symptomatic, Total commuters (also noninfected)
  - to_region_id_2
    - time: time points
    - total: Asymptomatic, Symptomatic, Total commuters (also noninfected) 
  - ...
- region_id_2
  - ...
```

The aggregated values `Asymptomatic, Symptomatic` could or should maybe be defined by some model<->graph interface to define which compartments are written out or aggregated here. Similarly, we may want to add some non-aggregation or partial aggregation on age groups or other demographic features used in the model.

This gives the ToDos:

- [ ] provide function that aggregates all age groups (social/demographic features) and only distinguishes between asymptomatic and symptomatic for the SECIRVVS model
- [ ] extend to other models (i.e., allow definition of assignment and aggregation of compartments)
- [ ] add some non-aggregation or partial aggregation on age groups or other demographic features used in the model
