### ISSUE TITLE
Redesigning flows

### ISSUE THREAD

**Issue by joergbrech** [SciCompMod/memilio#61]
Currently the hardest part of defining a custom compartmental model is prescribing the right hand side in `get_derivatives`. There are two other options to eleveate this:

1. Add an option to `add_flow`s in the ctor of the compartmental model. This has already been implemented in secir.h, but it is disabled by the pragma `USE_DERIV_FUNC` and out of date. We benchmarked this approach and noticed some bottlenecks that would have to get fixed. Also, it is harder to reuse variables across flows, e.g. the `icu_occupancy`. Therefore we would have to define a fancy interface for cached variables that can be reused without recalculation by all flows.
2. We stick to having the author of a custom compartmental model define the `get_derivatives` function to evaluate the right-hand side, but we provide some custom classes to help writing the function, e.g. a `Flow`. This way, variables that are used by all flows can be defined in the beginning of the function call, but we can still provide some level of abstraction with safeguards, e.g. to maintain the total population.

Some links:
 - Here is another more efficient implementation of `get_derivatives` by @dabele https://gitlab.dlr.de/hpc-against-corona/epidemiology/-/tree/292-experimental-refactor-of-secir-get-derivatives
 - Related issues in our Gitlab: 
    - https://gitlab.dlr.de/hpc-against-corona/epidemiology/-/issues/292
    - https://gitlab.dlr.de/hpc-against-corona/epidemiology/-/issues/139

**Comment by HenrZu** [comment]
Already adressed in PR #574 . So, we can close this.
