### ISSUE TITLE
History object can only log one thing at a time and other improvements

### ISSUE THREAD

**Issue by xsaschako** [SciCompMod/memilio#645]
### Motivation / Current Behaviour

We want to log multiple

### Enhancement description

Enhance the log option with a parameter pack T…

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by xsaschako** [comment]
@jubicker @DavidKerkmann 
This issue for suggestions

**Comment by jubicker** [comment]
The history object can only log once at the beginning of the simulation. As we have some information only at the end of a simulation, it would be useful to be able to log once at the end of the simulation.

**Comment by xsaschako** [comment]
related to #690
