### ISSUE TITLE
pd.read_json returns a ValueError instead of catched FileNotFoundError.

### ISSUE THREAD

**Issue by HenrZu** [SciCompMod/memilio#658]
### Bug description

https://github.com/DLR-SC/memilio/blob/ad29ab58ac94eef1554a6e6978125ec4dace33c5/pycode/memilio-epidata/memilio/epidata/getDataIntoPandasDataFrame.py#L176

When running getCommuterMobility.py with an empty pydata/germany folder, i get an ValueError instead of a FileNotFoundError which is not catched here.

 print(pd. __version__)
1.4.3

### Version

Windows

### To reproduce

Just launch the getCommuterMobility main with empty pydata/germany dir.

### Relevant log output

```zsh
Exception: ValueError
Expected object or value
```

### Checklist

- [ ] Attached labels, especially loc:: or model:: labels.
- [ ] Linked to project

**Comment by patricklnz** [comment]
I get a FileNotFoundError. Can you specify what you did? Was your read_data True or False? @HenrZu

**Comment by patricklnz** [comment]
This was changed in Pandas 1.5.
Since pandas 2.0.0 is required for memilio-epidata this Issue can be closed.
