### ISSUE TITLE
FutureWarnings in pycode with newly released pandas 2.1.1

### ISSUE THREAD

**Issue by patricklnz** [SciCompMod/memilio#773]
With he newly released Pandas version 2.1.1 a lot of Future Warning are printed accross all data download files.

Console Output:
In getDIVIData.py, getVaccinationData.py, getCaseData and getJHData.py
`FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.`

In getCommuterMobility.py 
`FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use ser.iloc[pos]`

In getVaccinationData.py
`FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.`

In modifyDataFrameSeries.py
`FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.`

There may be more FutureWarnings. This has to be checked.

**Comment by mknaranja** [comment]
@patricklnz I think this is a small but important issue to remove all the warnings.
