### ISSUE TITLE
Handle inconsistent data with different start dates

### ISSUE THREAD

**Issue by patricklnz** [SciCompMod/memilio#808]
In Issues #796, #806 & #807 inconsistent data were reported. It seems that there are multiple sources of error (for example cumulative sum or imputed dates).
We should discuss how to handle these.

**Comment by patricklnz** [comment]
@HenrZu @annawendler @mknaranja

As mentioned before in Issue #796 a crucial point is what `start_date` should mean and if data before `start_date` should be considered or not. Anyways, this would not solve all problems, as forward-filled data would still be missing then. Also, there could be a problem with the moving average (should the moving average consider data before `start_date`?)

If the start and end date are cut after `impute_and_reduce_df` is called, it would solve all problems but affect performance, so I don't see this as a good option.

For now, I would at least print warnings when the start date differs from the default value.

**Comment by HenrZu** [comment]
Thank you for opening this issue. I think we should generally try to look at only a subset, taking advantage of the fact that the data from the sources are already organized. 
Thereby we save computing time and memory size on the drive. 
I don't see any problems with the moving average. If needed, we can still use a few days before the Start_date/after End_date.

However, it can be confusing if the comulative numbers depend on the start_date value.

**Comment by mknaranja** [comment]
A message from the off :D

1. I would suggest to keep the last entry for each configuration (age, sex, number of vaccinations, id county, ...) before the start_day (e.g. at start_day - n, where n is arbitrary)
2. then to forward fill this last entry to the start_date. This happens either by direct insert to start date or as in 3.
3. If we do moving_average, we also need to fill some dates before the start_date (e.g. start_date - (ma-1)/2 for odd ma)
4. then to cut at start_date or (start_date - (ma-1)/2)
5. then to impute and compute ma if needed.
6. then to cut at start_date.

We would then still have total cumulative numbers and the time period (end-start) cumulative numbers can be obtained by substraction of the first value.

What do you think?
