### ISSUE TITLE
Link Brunswick data 

### ISSUE THREAD

**Issue by xsaschako** [SciCompMod/memilio#834]
### Feature description

we need to release the brunswick data.

for this we have some options which we should explore:

git large file storage
another repository

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project.

**Comment by xsaschako** [comment]
@mknaranja

**Comment by mknaranja** [comment]
The data set on microscopic trips for the Brunswick region has been uploaded to zenodo: https://zenodo.org/records/13318436

@xsaschako Please add the link to the data in the simulation ABM file. With that I close here.
