### ISSUE TITLE
change wording: replace abm migration by mobility and epi by mio

### ISSUE THREAD

**Issue by xsaschako** [SciCompMod/memilio#842]
### Provide a description of requested documentation changes.

Change all occurrences from migration to movement.

**Comment by xsaschako** [comment]
I'll probably also rename epi to mio while i'm at it

**Comment by xsaschako** [comment]
There are several phrases to change and we need to decide if we want to rename it into mobility or movement, e.g.:
- - Person::migrate_to
- migration
- MigrationEdge
- make_migration_sim
- time step of migration, daily migration every second step
- migration data
- migration_destination
- use_migration_rules
- apply_movement
- forward migration

**Comment by xsaschako** [comment]
We decided on:
- mobility if not a verb
- go (to) as a verb (comment functions with “mobility” keyword)

**Comment by DavidKerkmann** [comment]
> We decided on:
> 
> * mobility if not a verb
> * go (to) as a verb (comment functions with “mobility” keyword)

For now, I renamed everything to "movement" or "move_to". Didn't read this comment before doing so. I can redo it and call it mobility. Perhaps we decide on this quickly.

**Comment by DavidKerkmann** [comment]
Since there were still some unclear points and no perfect naming, we discussed in a group an propose:

- "mobility" if not a verb
- "commuted" for the "migrated" vector in the graph-ode parts (MobilityEdge)
- "change_location" for the ABM function to change a single persons location
- "perform_mobility" for the large ABM function that handles all the mobility

@mknaranja Do you agree with this?

**Comment by DavidKerkmann** [comment]
Instead of "commuted", we use "mobile_population".

**Comment by DavidKerkmann** [comment]
There are many appearances of "moved" or "move" that were previously "migrated" or "migrate" which relate to a verb, in particular in `memilio/cpp/memilio/mobility/metapopulation_mobility_instant.h`. We need to have a verb for these, if we use "mobile_population" as a noun.

**Comment by jubicker** [comment]
We only need verbs for the documentation right? Because the parameters "migrated", "return_migrated" etc. will be renamed to "mobile_population", "return_mobile_population". For the documentation verbs could be "change location" in the ABM and "change node" in the Graph model.
