### ISSUE TITLE
segfault in ABM with OpenMP

### ISSUE THREAD

**Issue by dabele** [SciCompMod/memilio#857]
### Bug description

OpenMP multithreaded abm_simulation crashes with a segfault. without OpenMP (or OMP_NUM_THREADS=1) the program runs normal. In Release build the crash happened reliably for me. In Debug builds the crash doesn't always happen or takes a long time to happen, so it's hard to debug

### Version

Linux

### To reproduce

1. build abm_simulation with MEMILIO_ENABLE_OPENMP=ON
2. `export OMP_NUM_THREADS=<N>`, higher N _seems_ to increase chance of it happening.
3. run `abm_simulation 1 <dir>`

### Add any relevant information, e.g. used compiler, screenshots.

```zsh
gcc 11, ubuntu 20
```

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by dabele** [comment]
Should probably prioritize adding unit tests with OpenMP: #786

**Comment by dabele** [comment]
Actually I found the error, it's the unordered_map in `TestingStrategy::m_location_to_schemes_map`. That should be resolved with #830. I will retest then.

**Comment by mknaranja** [comment]
@charlie0614 Was this maybe the problem you were facing?

**Comment by xsaschako** [comment]
> @charlie0614 Was this maybe the problem you were facing?

Yes, it was. I hadn't known about it either, so after we found what the issue was, Daniel showed us his resolution.
