### ISSUE TITLE
Handle engines for pandas.read_excel

### ISSUE THREAD

**Issue by patricklnz** [SciCompMod/memilio#910]
With the update to pandas 2.2.0 [(Documentation)](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html) the `read_excel` function fails with the openpyxl engine. 
Pandas have added a new engine `calamine` which can be up to 5x faster than openpyxl.
I think we should take that, but pandas versions smaller than that should also work with our programm

A possible solution would be checking the used pandas version and decide from that which engine to use.
`from distutils.version import LooseVersion

```
if LooseVersion(pd.__version) > LooseVersion(2.2.0):
    engine = 'calamine'
else:
    engine = 'openpyxl`
```

@mknaranja what's your opinion on that?

**Comment by mknaranja** [comment]
Sounds like a good solution.
