### ISSUE TITLE
Make the LCT SECIR model a derived class of FlowModel

### ISSUE THREAD

**Issue by lenaploetzke** [SciCompMod/memilio#914]
### Motivation / Current Behaviour
Currently the LCT model is not derived from a class. The functionality is similar to the FlowModel.
Also the files memilio/compartments/simulation.h for the CompartmentalModel and models/lct_secir/simulation.h for the LCT model do exactly the same. 
Both types of model should be combined.

### Enhancement description

It should be no problem to make the LCT SECIR model a derived class of FlowModel to have a consistent project structure.

### Additional context
For example: m_initial_values is used exactly like mio::CompartmentalModel::populations. If you want to, you could change its type to mio::Population, make the member public and rename it, so the models have more similar interface.

 _Originally posted by @reneSchm in https://github.com/SciCompMod/memilio/pull/941#discussion_r1502307064_

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by lenaploetzke** [comment]
The problem with the implemented approach was that CompartmentalModel needs a class derived from Populations for Pop. The logic would be to pass the LctInfectionState class to Populations.  However, Populations inherits from CustomIndexArray, so LctInfectionState is the "Tags" of CustomIndexArray. Using LctInfectionState as CustomIndexArray does not currently work.

**Comment by reneSchm** [comment]
You can maybe try and specialize Index<LctInfectionState>? IIRC, CustomIndexArray never instantiates the Tags directly, only an Index<Tag> for each Tag.
