### ISSUE TITLE
Refactor epidata to support ingestion into the LOKI database

### ISSUE THREAD

**Issue by MariamaJ** [SciCompMod/memilio#916]
### Feature description

Currently, public epidemiological data is downloaded and dumped into a json file. The aim of is ticket is to create an interface allowing the upload the downloaded epidemiological data into the LOKI specific SQL database

### Checklist

- [x] Attached labels, especially loc:: or model:: labels.
- [x] Linked to project.

**Comment by MariamaJ** [comment]
@mknaranja , I'm unable to add more labels to the issues.

**Comment by mknaranja** [comment]
@MariamaJ I added it to two boards and added more labels. If it is in progress, set it to in progress on the boards.

**Comment by MariamaJ** [comment]
Great! Thanks @mknaranja ! Can you also assign it to me?

**Comment by mknaranja** [comment]
I think you were not in both teams for memilio-development. Can you try if you are allowed now?

**Comment by MariamaJ** [comment]
It works! Thanks!
