### ISSUE TITLE
Rename world to model

### ISSUE THREAD

**Issue by DavidKerkmann** [SciCompMod/memilio#968]
### Motivation / Current Behaviour

As a subset of #400 we should rename the world to model to use identical names and patterns.

### Enhancement description

Renaming is done quickly. One should do the passing to the Simulation similar to the ODE models and think about templates for the world/model.

### Checklist

- [X] Attached labels, especially loc:: or model:: labels.
- [X] Linked to project

**Comment by mknaranja** [comment]
The `abm.h` could/should probably be removed and replaced by model.h then.
